defaults: &defaults
  adapter:  mysql

development:
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # LOCAL
  # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  database: peek_development
  adapter: mysql
  username: root
  password: 
  host:     localhost
  
  <<: *defaults
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # PLATFORM
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # database: titelbild
  # username: titelbild
  # password: trackingpw
  # host:     10.1.1.246
  # socket: /tmp/mysql.sock

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  mysql
  #     database: titelbild
  #     username: titelbild
  #     password: trackingpw
  #     host:     10.1.1.246
  #     socket: /tmp/mysql.sock

test:
  database: peek_test
  <<: *defaults
  
production:
  database: peek_production
  <<: *defaults
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # PLATFORM
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  database: titelbild
  username: titelbild
  password: trackingpw
  host:     10.1.1.246
  socket: /tmp/mysql.sock
